### ISSUE TITLE
No such file or directory @ rb_sysopen - https://api.github.com/repos/th-ch/youtube-music/releases/latest

### ISSUE THREAD

**Issue by LorenzoMorelli** [th-ch/homebrew-youtube-music#1]
Hi and thank you for your work!

I have seen this issue has been closed on main repository but I still get this error even by following both ways of installing youtube-music via brew explained in the new readme

**Comment by gmcinalli** [comment]
I've this error when upgrading via `brew upgrade --cask youtube-music`:

```
Error: th-ch/youtube-music/youtube-music: No such file or directory @ rb_file_s_rename - (/opt/homebrew/Caskroom/youtube-music/.metadata/v3.2.2, /opt/homebrew/Caskroom/youtube-music/.metadata/v3.2.2.upgrading)
```

**Comment by th-ch** [comment]
👋 It seems sometimes failing to upgrade (typically getting rate limited in the GH API) can lead to that weird situation - hopefully https://github.com/th-ch/homebrew-youtube-music/pull/3 will help, in the meantime feel free to `rm -rf /opt/homebrew/Caskroom/youtube-music/` then `brew install --cask th-ch/youtube-music/youtube-music` to go back to a clear state :)

**Comment by ZuBB** [comment]
> rm -rf /opt/homebrew/Caskroom/youtube-music/

This does the trick!

**Comment by ZuBB** [comment]
I just tried to update the app through Brew, and it bit me again. Any chance to fix it?

**Comment by th-ch** [comment]
https://github.com/th-ch/homebrew-youtube-music/pull/5 should fix the issue - closing, feel free to re-open if needed!
