### ISSUE TITLE
Unable to uninstall completely

### ISSUE THREAD

**Issue by teddythinh** [th-ch/homebrew-youtube-music#2]
Hi there, I want to uninstall youtube-music using `brew uninstall` command:

```sh
brew uninstall --cask youtube-music
```

But after I checked with the `brew list` command, it's still there although it says it has been uninstalled.

I also tried this command but it doesn't work

```sh
brew uninstall --cask th-ch/youtube-music/youtube-music
```

After all, I was able to uninstall using this command:

```sh
brew uninstall --force th-ch/youtube-music/youtube-music
```

**Comment by th-ch** [comment]
👋 Glad to hear `force` worked, I guess it depends on how it was installed (typically using `--cask` or not)  - hopefully with the instructions in https://github.com/th-ch/homebrew-youtube-music/pull/3 it should work better!
